name: anomaly_icme
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - backports=1.0=py_2
  - backports.weakref=1.0rc1=py35_0
  - blas=1.1=openblas
  - bleach=1.5.0=py35_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2016.9.26=py35_0
  - cffi=1.11.5=py35h5e8e0c9_1
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - freetype=2.7=1
  - html5lib=0.9999999=py35_0
  - intel-openmp=2020.1=217
  - jpeg=9d=h516909a_0
  - libedit=3.1.20191231=h46ee950_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h24d8f2e_14
  - libgfortran=3.0.0=1
  - libgomp=9.3.0=h24d8f2e_14
  - libpng=1.6.37=hed695b0_1
  - libprotobuf=3.5.2=hd28b015_1
  - libstdcxx-ng=9.3.0=hdf63c60_14
  - libtiff=4.0.10=hc3755c2_1005
  - lz4-c=1.9.2=he1b5a44_1
  - markdown=2.6.9=py35_0
  - mkl=2020.1=217
  - ncurses=6.2=he1b5a44_1
  - ninja=1.10.0=hc9558a2_0
  - numpy=1.14.6=py35_blas_openblashd3ea46f_200
  - olefile=0.46=py_0
  - openblas=0.2.20=8
  - openssl=1.0.2u=h516909a_0
  - pillow=4.0.0=py35_2
  - pip=20.2.1=py_0
  - protobuf=3.5.2=py35hd28b015_0
  - pycparser=2.20=pyh9f0ad1d_2
  - python=3.5.5=h5001a0f_2
  - python-dateutil=2.8.1=py_0
  - pytorch=1.2.0=py3.5_cuda10.0.130_cudnn7.6.2_0
  - readline=7.0=hf8c457e_1001
  - scipy=1.1.0=py35_blas_openblash7943236_201
  - setuptools=36.4.0=py35_1
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.32.3=h62c20be_0
  - tensorflow=1.3.0=0
  - tensorflow-base=1.3.0=py35h79a3156_1
  - tensorflow-tensorboard=1.5.1=py35hf484d3e_1
  - tk=8.6.10=hed695b0_0
  - torchvision=0.1.8=py35_0
  - tqdm=4.48.2=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.5=h6597ccf_2
prefix: /home/tu-wan/anaconda3/envs/anomaly_icme

